import { Team } from './types';

// Curated pool of EA FC 26 teams with colors and emoji flags
export const AVAILABLE_TEAMS: Team[] = [
  // Elite Clubs
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    shortName: 'RMA',
    emoji: '👑',
    primaryColor: '#FEBE10',
    secondaryColor: '#FFFFFF',
    country: 'Spain',
    type: 'club',
    league: 'La Liga',
    rating: 91,
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'BAR',
    emoji: '🔵🔴',
    primaryColor: '#A50044',
    secondaryColor: '#004D98',
    country: 'Spain',
    type: 'club',
    league: 'La Liga',
    rating: 89,
  },
  {
    id: 'man-city',
    name: 'Manchester City',
    shortName: 'MCI',
    emoji: '🔵',
    primaryColor: '#6CABDD',
    secondaryColor: '#FFFFFF',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 90,
  },
  {
    id: 'man-utd',
    name: 'Manchester United',
    shortName: 'MUN',
    emoji: '🔴',
    primaryColor: '#DA020E',
    secondaryColor: '#FFE500',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 83,
  },
  {
    id: 'liverpool',
    name: 'Liverpool FC',
    shortName: 'LIV',
    emoji: '❤️',
    primaryColor: '#C8102E',
    secondaryColor: '#F6EB61',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 88,
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'ARS',
    emoji: '🔴',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 86,
  },
  {
    id: 'chelsea',
    name: 'Chelsea FC',
    shortName: 'CHE',
    emoji: '💙',
    primaryColor: '#034694',
    secondaryColor: '#FFFFFF',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 84,
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    emoji: '🗼',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
    country: 'France',
    type: 'club',
    league: 'Ligue 1',
    rating: 88,
  },
  {
    id: 'bayern',
    name: 'Bayern Munich',
    shortName: 'BAY',
    emoji: '⚪🔴',
    primaryColor: '#DC052D',
    secondaryColor: '#0066B2',
    country: 'Germany',
    type: 'club',
    league: 'Bundesliga',
    rating: 89,
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    emoji: '🟡⚫',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
    country: 'Germany',
    type: 'club',
    league: 'Bundesliga',
    rating: 84,
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUV',
    emoji: '⬛⬜',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    country: 'Italy',
    type: 'club',
    league: 'Serie A',
    rating: 83,
  },
  {
    id: 'inter-milan',
    name: 'Inter Milan',
    shortName: 'INT',
    emoji: '🖤🔵',
    primaryColor: '#010E80',
    secondaryColor: '#000000',
    country: 'Italy',
    type: 'club',
    league: 'Serie A',
    rating: 87,
  },
  {
    id: 'ac-milan',
    name: 'AC Milan',
    shortName: 'MIL',
    emoji: '❤️⚫',
    primaryColor: '#FB090B',
    secondaryColor: '#000000',
    country: 'Italy',
    type: 'club',
    league: 'Serie A',
    rating: 85,
  },
  {
    id: 'atletico',
    name: 'Atlético Madrid',
    shortName: 'ATM',
    emoji: '🔴⚪',
    primaryColor: '#CE3524',
    secondaryColor: '#272E61',
    country: 'Spain',
    type: 'club',
    league: 'La Liga',
    rating: 86,
  },
  {
    id: 'napoli',
    name: 'SSC Napoli',
    shortName: 'NAP',
    emoji: '🔵',
    primaryColor: '#12A0C3',
    secondaryColor: '#FFFFFF',
    country: 'Italy',
    type: 'club',
    league: 'Serie A',
    rating: 84,
  },
  {
    id: 'porto',
    name: 'FC Porto',
    shortName: 'POR',
    emoji: '🔵⚪',
    primaryColor: '#003087',
    secondaryColor: '#FFFFFF',
    country: 'Portugal',
    type: 'club',
    league: 'Primeira Liga',
    rating: 82,
  },
  {
    id: 'benfica',
    name: 'SL Benfica',
    shortName: 'BEN',
    emoji: '🦅',
    primaryColor: '#DA291C',
    secondaryColor: '#FFFFFF',
    country: 'Portugal',
    type: 'club',
    league: 'Primeira Liga',
    rating: 82,
  },
  {
    id: 'ajax',
    name: 'Ajax',
    shortName: 'AJX',
    emoji: '🔴⬜',
    primaryColor: '#D2122E',
    secondaryColor: '#FFFFFF',
    country: 'Netherlands',
    type: 'club',
    league: 'Eredivisie',
    rating: 80,
  },
  {
    id: 'tottenham',
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    emoji: '⚪',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 82,
  },
  {
    id: 'newcastle',
    name: 'Newcastle United',
    shortName: 'NEW',
    emoji: '⬛⬜',
    primaryColor: '#241F20',
    secondaryColor: '#FFFFFF',
    country: 'England',
    type: 'club',
    league: 'Premier League',
    rating: 83,
  },

  // National Teams
  {
    id: 'brazil',
    name: 'Brazil',
    shortName: 'BRA',
    emoji: '🇧🇷',
    primaryColor: '#009C3B',
    secondaryColor: '#FEDD00',
    country: 'Brazil',
    type: 'national',
    rating: 88,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    shortName: 'ARG',
    emoji: '🇦🇷',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    country: 'Argentina',
    type: 'national',
    rating: 89,
  },
  {
    id: 'france',
    name: 'France',
    shortName: 'FRA',
    emoji: '🇫🇷',
    primaryColor: '#0055A4',
    secondaryColor: '#EF4135',
    country: 'France',
    type: 'national',
    rating: 87,
  },
  {
    id: 'england',
    name: 'England',
    shortName: 'ENG',
    emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    primaryColor: '#FFFFFF',
    secondaryColor: '#CF081F',
    country: 'England',
    type: 'national',
    rating: 85,
  },
  {
    id: 'spain',
    name: 'Spain',
    shortName: 'ESP',
    emoji: '🇪🇸',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    country: 'Spain',
    type: 'national',
    rating: 87,
  },
  {
    id: 'germany',
    name: 'Germany',
    shortName: 'GER',
    emoji: '🇩🇪',
    primaryColor: '#000000',
    secondaryColor: '#DD0000',
    country: 'Germany',
    type: 'national',
    rating: 85,
  },
  {
    id: 'portugal',
    name: 'Portugal',
    shortName: 'POR',
    emoji: '🇵🇹',
    primaryColor: '#006600',
    secondaryColor: '#FF0000',
    country: 'Portugal',
    type: 'national',
    rating: 84,
  },
  {
    id: 'italy',
    name: 'Italy',
    shortName: 'ITA',
    emoji: '🇮🇹',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
    country: 'Italy',
    type: 'national',
    rating: 84,
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    shortName: 'NED',
    emoji: '🇳🇱',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    country: 'Netherlands',
    type: 'national',
    rating: 84,
  },
  {
    id: 'belgium',
    name: 'Belgium',
    shortName: 'BEL',
    emoji: '🇧🇪',
    primaryColor: '#EF3340',
    secondaryColor: '#000000',
    country: 'Belgium',
    type: 'national',
    rating: 83,
  },
];

export function getTeamById(id: string): Team | undefined {
  return AVAILABLE_TEAMS.find((t) => t.id === id);
}

export function getTeamsByType(type: 'club' | 'national'): Team[] {
  return AVAILABLE_TEAMS.filter((t) => t.type === type);
}
